# These are supported funding model platforms 
WhatsApp: [Nekotina](https://wa.me/5215625060788
patreon: NekoPay 
open_collective: NekoPay with a single Open Collective username
ko_fi: NekoPay with a single Ko-fi username
tidelift: NekoPay with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: NekoPay with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: NekoPay with a single IssueHunt username
otechie: NekoPay with a single Otechie username
custom: ['https://wa.me/5215625060788']
